### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by yorrd** [kevinpschaaf/wc-ssr#1]
@kevinpschaaf heyo. I just found this by accident. Is this something which could be working with a few adjustments or are we off by a lot? I'm just wondering if we could hypothetically get SSR to work on Polymer because there are - as far as I can see - no valid options right now. I would love to write a few pull requests to this if we can get it to work :)

**Comment by kevinpschaaf** [comment]
This was just an exploration... There are 3 hard parts with SSR'ing WC's:

1. Generating the expanded DOM structure on the server (e.g. jsdom doesn't yet support V1 CE/SD API)
2. Serializing the shadow tree and re-creating it on the client (there is no declarative SR in the platform)
3. "Re-hydrating" custom elements with their DOM

This experiment really only covers (2).  (1) is just a matter of time/effort, and I've been able to get the CE polyfill running in jsdom.  The problem is really with (3), especially in Polymer 1/2's templating system, since it's a challenge to associate inner template instances (e.g. DOM stamped with `dom-repeat`/`dom-if`) with the structures representing them in memory without a lot of work/changes to the library.  Then because the hydration scheme is specific to the rendering library, it would only be a "Polymer SSR" solution, not general WC solution.

I've done a couple rounds of thought exercises on this but haven't had the time to focus on what a good up-front design would need.

This is definitely something we're considering more for `lit-html` and considering how the underlying new specs (e.g. `TemplateInstantiation`) should accommodate the needs of SSR.

**Comment by yorrd** [comment]
Well, thanks for the very informative insight! I guess I'm going to wait for Polymer 3 to release first and then see whether I can help in any way. (Btw, I'd really appreciate an update on that, at the moment we rely heavily on your team's statement concerning the end of Q1 as a RC. No pressure, just clarity on the roadmap would be nice :) )

**Comment by kevinpschaaf** [comment]
Keep an eye on the blog; latest status post went out on Friday: https://www.polymer-project.org/blog/2018-03-23-polymer-3-latest-preview.html
